server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://lh-postgres:5432/db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
